services:
  db:
    image: mysql:latest
    container_name: stock-db
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mysql-dev-data:/var/lib/mysql

volumes:
  mysql-dev-data:
