services:
  app:
    build:
      dockerfile: Dockerfile
    image: stock
    container_name: stock
    restart: on-failure
    ports:
      - 8080:80
    networks:
      - stocknet
    env_file:
      - .prod.env

  db:
    image: mysql:latest
    container_name: stock-db
    networks:
      - stocknet
    env_file:
      - .prod.env
    volumes:
      - mysql-dev-data:/var/lib/mysql

networks:
  stocknet:
    name: stocknet
    driver: bridge

volumes:
  mysql-dev-data:
